version: "3.9"

services:
  greetings-api:
    container_name: greetings-api
    image: ${REGISTRY:-greetings-camunda}/greetings-api:${TAG:-latest}
    build:
      context: ../../src/api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - MQTT_HOST=${MQTT_HOST:-localhost}
      - MQTT_PORT=${MQTT_PORT:-1883}
    ports:
      - "6543:80"     # app
      - "6643:3500"   # dapr http
      - "65430:50001" # dapr grpc
      - "9999:9090"   # dapr metrics

  greetings-api-dapr:
    container_name: greetings-api-dapr
    image: daprio/daprd:1.9.0
    network_mode: "service:greetings-api"
    command: ["./daprd",
      "-app-id", "greetings-api",
      "-app-port", "80",
      "-dapr-http-port", "3500",
      "-dapr-grpc-port", "50001",
      "-metrics-port", "9090",
      "-placement-host-address", "dapr-placement:50006", 
      "-components-path", "/components"
      ]
    depends_on:
      - greetings-api
    volumes:
      - "../../dapr/components/:/components"
      - "../../dapr/configuration/:/configuration"
  
  dapr-placement:
    container_name: dapr-placement
    image: daprio/dapr:1.9.0
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"

networks:
  default:
    name: camunda-cloud
    external: true