apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: greet
  namespace: greetings-camunda
spec:
  type: bindings.zeebe.jobworker
  version: v1
  metadata:
  - name: gatewayAddr
    value: host.docker.internal:26500
  - name: gatewayKeepAlive
    value: 45s
  - name: usePlainTextConnection
    value: true
  - name: jobType
    value: greet
  - name: workerName
    value: greeter-worker
  - name: workerTimeout
    value: 30s  # defaults to 5m
  - name: requestTimeout
    value: 10s  # defaults to 30s
  scopes:
    - greetings-api
