apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mqtt
spec:
  type: pubsub.mqtt
  version: v1
  metadata:
  - name: consumerID
    value: "{uuid}"
  - name: url
    value: mqtt://host.docker.internal:1883
  - name: qos
    value: 1
  - name: retain
    value: false
  - name: cleanSession
    value: true
  - name: backOffMaxRetries
    value: 0