apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: host.docker.internal:6379
  - name: redisPassword
    secretKeyRef: 
      name: redis.password
      key: redis.password
  - name: actorStateStore
    value: "true"
auth:
  secretStore: secrets